export const SET_LOADING = 'USER ACTION SET LOADING';

export const SET_CURRENT_PATH = 'USER ACTION SET CURRENT PATH';
export const SET_CURRENT_USER = 'USER ACTION SET CURRENT USER';
export const SET_CHECKING = 'USER ACTION SET CHECKING';
export const LOGOUT = 'USER ACTION LOGOUT';
export const SET_USERS = 'USER ACTION SET USERS';
export const SET_ACCOUNTS = 'USER ACTION SET ACCOUNTS';
export const SET_ACCOUNT_INTERVALID = 'USER ACTION SET ACCOUNT INTERVAL ID';
export const SET_QUOTE_INTERVALID = 'USER ACTION SET QUOTE INTERVAL ID';
export const SET_QUOTE = 'USER ACTION SET QUOTE';
export const SET_DEPOSIT_ADDRESS = 'USER ACTION SET SET DEPOSIT ADDRESS';